on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.14.6"
      - run: go test ./...
      - run: CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' .
      - uses: actions/upload-artifact@v2
        with:
          name: srv-announcer
          path: ./srv-announcer
